version: 2.1

orbs:
  windows: circleci/windows@5.0
alias_anchors: # anchors must be defined in YAML before being used by an alias
  - &should_sign
    or:
      - equal: [ develop, << pipeline.git.branch >> ]
      - equal: [ main, << pipeline.git.branch >> ]
workflows:
  version: 2
  build:
    jobs:
      - build-mac:
          context: scratch-desktop-and-link
      - build-win:
          context: scratch-desktop-and-link
jobs:
  build-mac:
    macos:
      xcode: 14.2 # warning MM0079: The recommended Xcode version for Xamarin.Mac 9.0.0 is Xcode 14.1 or later.
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1 # save some time
    steps:
      - checkout
      - run:
          name: Build Safari helper
          command: |
            xcodebuild -project "Scratch Link Safari Helper/Scratch Link Safari Helper.xcodeproj" -scheme "Scratch Link Safari Helper" clean build
      - restore_cache:
          keys:
            - visual-studio-mac-{{ checksum ".circleci/install-or-extract-vs-mac.sh" }}
      - run:
          name: Install/Extract Visual Studio for Mac
          command: |
            # CACHE_ARCHIVE must match the path in save_cache
            CACHE_ARCHIVE="/tmp/visual-studio-mac.tar.gz"
            bash ./.circleci/install-or-extract-vs-mac.sh "$CACHE_ARCHIVE"
      - save_cache:
          key: visual-studio-mac-{{ checksum ".circleci/install-or-extract-vs-mac.sh" }}
          paths: # Caching an archive instead of loose files works around CircleCI's issues with extracting links and permissions on macOS
            - /tmp/visual-studio-mac.tar.gz
      - unless:
          condition:
            *should_sign
          steps:
            - do_mac_build:
                configuration: Debug
                artifact_tag: Debug
      - when:
          condition:
            *should_sign
          steps:
            - add_ssh_keys
            - run:
                name: Import CI context
                command: fastlane circleci
            - do_mac_build:
                configuration: Release_DevID
                artifact_tag: notarizeMe # see below
            - do_mac_build:
                configuration: Release_MAS
                artifact_tag: MAS
            - run:
                name: Notarize Developer ID build
                command: |
                  for PKGPATH in Artifacts/"Scratch Link-notarizeMe"*.pkg; do
                    PKGFILE="${PKGPATH##*/}"
                    scratch-link-mac/notarize.sh edu.mit.scratch.scratch-link "${PKGPATH}" "${PKGPATH}" /tmp || rm -f "${PKGPATH}"
                    mv -v "${PKGPATH}" "Artifacts/${PKGFILE/Scratch Link-notarizeMe/Scratch Link}"
                  done
      - store_artifacts:
          path: Artifacts/
  build-win:
    executor: windows/server-2022 # Windows Server with Visual Studio 2022
    steps:
      - checkout
      - unless:
          condition:
            *should_sign
          steps:
            - do_win_build:
                configuration: Debug
                artifact_tag: Debug
      - when:
          condition:
            *should_sign
          steps:
            - do_win_build:
                configuration: Release
      - store_artifacts:
          path: Artifacts/
commands:
  do_mac_build:
    parameters:
      configuration:
        default: "Release"
        type: string
      artifact_tag:
        default: ""
        type: string
    steps:
      - run:
          name: "Build for Mac: <<parameters.configuration>>"
          command: |
            # installing Visual Studio put some new path files into /etc/path.d
            # some CircleCI images automatically load those new files for us, some don't
            # run `path_helper` here to make sure the path to `msbuild` is in $PATH
            eval `/usr/libexec/path_helper -s`
            msbuild -m -t:Restore -p:Configuration=<<parameters.configuration>>_Mac scratch-link.sln
            "/Applications/Visual Studio.app/Contents/MacOS/vstool" build -t:Build -c:<<parameters.configuration>>_Mac "${PWD}/scratch-link.sln"
            # "for" is just a convenient way to resolve the glob to a variable so we can DRY the filename for "if" and "mv"
            for PKGPATH in scratch-link-mac/bin/<<parameters.configuration>>/"Scratch Link"*.pkg; do
              if [ -r "$PKGPATH" ]; then
                PKGFILE="${PKGPATH##*/}"
                if [ -n "<<parameters.artifact_tag>>" ]; then
                  PKGFILE="${PKGFILE/Scratch Link/Scratch Link-<<parameters.artifact_tag>>}"
                fi
                mkdir -p Artifacts
              fi
              # this is outside the "if" to force an error if the file doesn't exist
              mv -v "$PKGPATH" "Artifacts/${PKGFILE}"
            done
  do_win_build:
    parameters:
      configuration:
        default: "Release"
        type: string
      artifact_tag:
        default: ""
        type: string
    steps:
      - run:
          name: "Build for Windows: <<parameters.configuration>>"
          command: |
            # Build the MSIX project instead of the Solution because msbuild gets grumpy about the Mac project.
            # That means SolutionDir needs to be set artificially, though.
            # The `UapAppxPackageBuildMode=StoreAndSideload` means it'll build both MSIXUpload and MSIXBundle.
            # The StoreUpload mode does that too, but that might be a bug, and semantically "StoreAndSideload" is what we want.
            msbuild scratch-link-win-msix/scratch-link-win-msix.wapproj -maxCpuCount -restore -t:Build -p:SolutionDir="$PWD\" -p:Configuration="<<parameters.configuration>>_Win" -p:AppxBundlePlatforms="x86|x64|ARM64" -p:AppxBundle=Always -p:UapAppxPackageBuildMode=StoreAndSideload
      - run:
          name: "Move Windows artifacts: <<parameters.configuration>>"
          shell: bash
          command: |
            mkdir -p Artifacts
            # The store package is fine as is: no user will see this filename.
            mv -v scratch-link-win-msix/AppPackages/scratch-link-win-msix_*_<<parameters.configuration>>_Win.msixupload Artifacts/
            # Transform the bundle for a more user-friendly filename
            for PKGPATH in scratch-link-win-msix/AppPackages/scratch-link-win-msix_*_<<parameters.configuration>>_Win_Test/scratch-link-win-msix_*_<<parameters.configuration>>_Win.msixbundle; do
              if [ -r "$PKGPATH" ]; then
                PKGFILE="${PKGPATH##*/}"
                [[ $PKGFILE =~ scratch-link-win-msix_([.0-9]+)_(.*)_<<parameters.configuration>>_Win.msixbundle$ ]]
                PKGVERSION=${BASH_REMATCH[1]}
                PKGPLATFORMS=${BASH_REMATCH[2]}
              fi
              # do the move outside the "if" above to force an error if the file doesn't exist
              if [ -z "<<parameters.artifact_tag>>" ]; then
                mv -v "$PKGPATH" "Artifacts/Scratch Link ${PKGVERSION}.msixbundle"
              else
                mv -v "$PKGPATH" "Artifacts/Scratch Link ${PKGVERSION} <<parameters.artifact_tag>>.msixbundle"
              fi
            done
